quil-lang/quilc

app/src/impl/sbcl.lisp
src/parser.lisp

- looks more stylish etc.
- stylewarning told me to do it.

Replace verbose cond typep with typecase.

---

doc/man/quilc.1

Add rpcq to manpage. Fixes #37.

Add rpcq to manpage

---

app/src/entry-point.lisp
doc/man/quilc.1

Choose logging level with --log-level. Any log levels above this (less
severe) will not be logged.
Quiet non-logging output with --quiet.

add --log-level and --quiet

---

src/addresser/initial-rewiring.lisp
src/chip-specification.lisp
src/pragmas.lisp
tests/initial-rewiring-tests.lisp

Rewire any dead qubits when using partial initial rewiring

---

src/compilers/translators.lisp
src/compressor/rewriting-rule-data-type.lisp
src/compressor/rewriting-rules.lisp
src/operator-bind.lisp

document make-rewriting-rule, other reorganizing

---

app/src/entry-point.lisp
app/src/rpc-server.lisp
app/src/versions.lisp
app/src/web-server.lisp

I don't think this requires any changes to pyquil.
Closes #163

Consolidate versions of quilc and cl-quil

---

build-app.lisp

compress core when compression is available

---

src/parser.lisp

Error on malformed parameter lists to DEFGATE and DEFCIRCUIT

---

src/analysis/resolve-applications.lisp
src/parser.lisp

The first commit fixes a nasty backtrace output, the other two are relatively cosmetic.

More improved error messages

---

Makefile
build-app.lisp

It turns out this was the cause of and closes #178.

Don't require SSL for drakma

---

README.md

Add ZeroMQ to README.md requirements section

---

src/ast.lisp
src/define-pragma.lisp
src/package.lisp

Fixes #171 
and now also
Fixes #198

Extend format-complex to optionally print in polar form

---

app/src/entry-point.lisp
app/src/rpc-server.lisp

e.g. using --host 127.0.0.1 restricts incoming connections to those
from localhost

Configure host with --host

---

README.md
app/src/entry-point.lisp
app/src/rpc-server.lisp
app/src/web-server.lisp
app/tests/rpcq-tests.lisp
src/analysis/process-includes.lisp
src/cfg.lisp
src/cl-quil.lisp
src/clifford/benchmarking-procedures.lisp
src/package.lisp
src/parser.lisp
tests/analysis-tests.lisp
tests/approximation-tests.lisp
tests/cfg-tests.lisp
tests/classical-memory-tests.lisp
tests/compilation-tests.lisp
tests/compiler-hook-tests.lisp
tests/initial-rewiring-tests.lisp
tests/misc-tests.lisp
tests/parser-tests.lisp
tests/state-prep-tests.lisp
tests/translator-tests.lisp
tests/typed-memory-tests.lisp
tests/utilities.lisp

parse-quil -> parse-quil-into-raw-program
parse-quil-string -> parse-quil
Closes #146

Rename parse-quil and parse-quil-string

---

README.md

Update Slack link in README to https://rigetti-forest.slack.com

---

cl-quil.asd
src/compilers/approx.lisp
src/compilers/optimal-2q.lisp
src/compressor/compressor.lisp
src/gates.lisp
src/package.lisp
src/relabeling.lisp

remove make-gate-matrix-from-gate-string in favour of make-matrix-from-quil

---

app/src/entry-point.lisp
app/src/rpc-server.lisp

Items before merging:
Tagging @appleby since I can't add them as a reviewer directly.
Closes #238.

Add *protoquil* to bordeaux-threads:*default-special-bindings*

---

app/src/versions.lisp
app/tests/misc-tests.lisp

I thought I had pushed this to the other branch. Didn't properly auth to github, however, so it never got in.

Pass proxy to latest-sdk-version

---

elf-library/Makefile
elf-library/build.lisp
elf-library/example.c

- shared library
- static library
- example run

buildsystem: add example makefile for interop C with Lisp

---

cl-quil-tests.asd
src/matrix-operations.lisp
tests/misc-tests.lisp

Test MEASURE semantics

---

src/chip-specification.lisp
src/compilers/approx.lisp
src/compilers/ucr-explode.lisp
src/matrix-operations.lisp

Fix numerical instability in diagonalizer-in-e-basis

---

src/compilation-methods.lisp

This reverts commit e66d847aac27955dde67458a42f9b114f35e8040.
Fixes #293

Revert "kill the remaining part of #271 that escaped obliteration"

---

README.md

Add git submodule note to the README

---

src/compilers/ucr-explode.lisp

Previously the description would only be true if F = Finv. But it is also true for unitary F.

Clarify description of expansion of FORKED into average of CONTROLLED

---

app/src/rpc-server.lisp
app/tests/rpcq-tests.lisp

Previously this would not resolve stuff like circuits

Fully parse quil in quil-to-native-quil endpoint

---

src/parser.lisp

This is just a bit of tidying. The easy case in the parser is that it is consuming a single line, dispatching on the first token and consuming a fixed template of successors (some required, some optional). This adds a simple bit of syntax for this.

Add MATCH-LINE macro

---

src/compilers/optimal-2q.lisp
src/define-compiler.lisp

DECLAIM defined compilers as FUNCTIONs

---

src/compressor/rewriting-rules.lisp

Better than Euler-compiling `I`...

eliminate identities via rewriting rule

---

src/chip-reader.lisp

The pyQuil tests have been QPU descriptors with `specs` layers containing misordered ISA keys all along. This PR extends quilc's tolerance toward this, though it still scolds with a warning.

accept misordered ISA keys

---

src/chip-reader.lisp

I forgot to sneak this warning into #362 .

warn on misordered keys

---

src/clifford/pauli.lisp
src/compilation-methods.lisp
src/compressor/compressor.lisp
src/package.lisp
src/utilities.lisp
tests/package.lisp

Fix governed queue creation and other portability fixes

---

app/src/entry-point.lisp
src/ast.lisp

Fix whitelist/blacklist checking

---

boondoggle/boondoggle-tests.asd

Add sapaclisp to boondoggle-tests dependencies

---

Makefile

Remove addition of ZMQ apt repo in install-test-deps

---

src/addresser/initial-rewiring.lisp
tests/initial-rewiring-tests.lisp

Previously, `PROG-INITIAL-REWIRING-HEURISTIC` only considered `GATE-APPLICATION`s when attempting to guess the initial rewiring. This resulted in a bad initial rewiring guess of `:NAIVE` when all the program's `GATE-APPLICATION`s (possibly 0) were `%NAIVELY-APPLICABLE-P`, but the program included a `MEASURE` or `RESET-QUBIT` instruction that was not `%NAIVELY-APPLICABLE-P`.
See also:
https://github.com/rigetti/quilc/pull/380
https://github.com/rigetti/quilc/issues/361

Include RESET-QUBIT and MEASURE in PROG-INITIAL-REWIRING-HEURISTIC

---

Dockerfile
Makefile
app/src/entry-point.lisp
build-app.lisp

While we work out some distribution kinks.

Temporarily disable tweedledum

---

src/clifford/pauli.lisp
src/package.lisp

Adds a routine not unlike `exponential_map` in pyQuil. Depends on #472.
Not sure if I got the signs right and will require some careful math review.

exponentiation of Paulis

---

cl-quil-tests.asd
tests/clifford-tests.lisp

Write unit test for EXP-PAULI.

---

tests/translator-tests.lisp

* resolves https://github.com/rigetti/quilc/issues/527

print compiler name if it cannot be tested

---

src/analysis/expansion.lisp
src/ast.lisp
tests/defcircuit-tests.lisp

Support CONTROLLED as a circuit modifier.

---

app/tests/rpcq-tests.lisp

This is the corresponding change mirroring https://github.com/rigetti/rpcq/pull/113 to unblock EC2 gitlab runners for quilc.

KILL-THREAD-SLOWLY in RPCQ tests

---

src/addresser/astar-rewiring-search.lisp

Credit where credit is due:
https://github.com/rigetti/quilc/pull/549#discussion_r367117727
https://github.com/rigetti/quilc/pull/452

Add periods to sentences without periods (pt. II)

---

src/parser.lisp
tests/good-test-files/good-defcircuit-shadow.quil
tests/good-test-files/good-defgate-pauli-sum-shadow.quil

This fixes the issue described in https://github.com/rigetti/qvm/issues/236

fix formal shadowing issue

---

src/ast.lisp
src/chip/chip-specification.lisp
src/cl-quil.lisp
src/classical-memory.lisp
src/define-compiler.lisp
src/package.lisp
src/utilities.lisp

Cleanups based on the report in #566

Add some more docstrings

---

src/define-compiler.lisp
tests/compilation-tests.lisp
tests/qpu-test-files/1q-wildcard-arguments.qpu

Fix compiler crawler wildcards

---

src/define-compiler.lisp
tests/compilation-tests.lisp

Fix rz/rx string reduction

---

src/compilers/linear-paulis.lisp

Use hermitian-eig rather than eig

---

app/src/entry-point.lisp
benchmarking/qasm-benchmarks.lisp
benchmarking/rewiring-analysis.lisp
benchmarking/suite.lisp
src/ast.lisp
src/compilation-methods.lisp
src/package.lisp
src/pragmas.lisp

COMPILER-HOOK *does not* mutate and *does* compress qubits

---

src/ast.lisp
src/package.lisp

Off by default.
How do you feel about this?

Add PRINT-OBJECT for PARSED-PROGRAMs which prints the program

---

src/define-compiler.lisp

This commit doesn't change the how any existing functionality works,
but does permit new functionality.
Currently, INST & co may only be used lexically within a WITH-INST,
and by extension, within DEFINE-COMPILER. If INST is used outside of
either of those contexts, there will be a _compile-time_ error it can
be detected, but definitely a run-time error.
This commit allows INST to be used anywhere within the dynamic extent
of WITH-INST (and DEFINE-COMPILER). This means it's now possible to
write functions like:
(defun inst-hadamard (N)
(dotimes (q N)
(inst "H" () q)))
There are two downsides:
- Compile-time errors cannot be detected since any INST call may
possible be valid.
- There may be a small performance penalty using dynamic
features. However, what we lost in making it dynamic might …

allow INST to be used dynamically

---

benchmarking/package.lisp
benchmarking/qaoa-tests/generate-program.lisp
benchmarking/qaoa-tests/qaoa-bench.lisp
cl-quil-benchmarking.asd

Moves some benchmarking-related stuff into the benchmarking package.

Add GENERATE-NATURAL-QAOA-PROGRAM to benchmarking package

---

README.md

Include IRC #qlisp in README

---

tests/benchmarking-procedures-tests.lisp

Test was failing on a fast machine because the "slow" case took 1/2
msec or less on every iteration. Time-it macro would round the time
down to zero in an effort to return time in milliseconds, needlessly
throwing away the extra precision in internal time units.
There's no need for any particular time units (such as msec), since
the time is only used for comparison.
Furthermore, it should use get-internal-run-time, not -real-time,
i.e., should not be affected by other processes running.
Changed time-it to return time in terms of internal time units and to
be in terms of run time.  Also, added some documentation of what it
does.
Also, the test code only tested whether the slow case took longer at
all. Improved it to test that the slow test takes longer by some
minimum slow-to-fast time …

Fix test-memoize-pauli-basis-matrices timing issues.

---

src/cfg.lisp
tests/cfg-tests.lisp

Take a look at the included test for a program where (currently) a `RESET` that precedes a `PRAGMA PRESERVE-BLOCK` is dropped.

Don't drop an empty RESET-BLOCK when processing a PRESERVED-BLOCK

---

src/qasm.lisp
tests/qasm-tests.lisp

Treats #prama <thing> as a Quil PRAGMA <thing>

qasm: support #pragma directives

---

src/compilers/translators.lisp
tests/compiler-hook-tests.lisp

allow DAGGER of a standard parametric gate

---

cl-quil.asd
src/analysis/resolve-objects.lisp
src/analysis/validate-seq-gate.lisp
src/analysis/validate-sequence-gate.lisp
src/ast.lisp
src/cl-quil.lisp
src/gates.lisp
src/parser.lisp
tests/bad-test-files/bad-defgate-as-sequence-circular.quil
tests/bad-test-files/bad-defgate-as-sequence-non-gate-application.quil
tests/bad-test-files/bad-defgate-as-sequence-references-qubit.quil
tests/bad-test-files/bad-defgate-as-sequence-self-referential.quil
tests/good-test-files/good-defgate-as-sequence-nested-defs.quil
tests/good-test-files/good-defgate-as-sequence-unused-arg.quil
tests/good-test-files/good-defgate-as-sequence.quil

Proposed implementation of defgate as sequence outlined in issue #762 
This adds syntax to Quil and rudimentary integration with the compilation pipeline.

Defgate as sequence

---

lib/src/libquilc.lisp

See quil-lang/sbcl-librarian#28.

Use new handler-bind error map in libquilc

---

src/magicl-constructors.lisp
tests/clifford-tests.lisp

Some weirdness was encountered in trying to rewrite some of the stdgates as pauli sums, this PR attempts to fix that weirdness and add tests

Rework pauli behavior and add tests

---

cl-quil.asd
src/discrete/numeric/utilities.lisp
src/discrete/operators/gates1.lisp
src/discrete/operators/pauli.lisp
src/discrete/package.lisp
src/discrete/rz-approx/generate-solution.lisp
tests/discrete/rz-approx-tests.lisp
tests/discrete/suite.lisp

Takes into account a few changes to Into instances and integer return types.
Requires: https://github.com/coalton-lang/coalton/pull/683

Update `cl-quil/discrete` to latest version of Coalton

---

src/addresser/logical-schedule.lisp

Noticed that a couple functions were suspiciously similar. Adding commuting blocks to the schedule is not all that different than adding any other kind of instruction; just delay adding the new threads to the top and bottom of the lschedule until after all the threads have been added.
One question: Why are `COMMUTING_BLOCK`s that use the `+IMPOSSIBLY-FULL-RESOURCE+` disallowed? I didn't notice anything in `logical-scheduler.lisp` that would fail.

Deduplicate code in logical-schedule

---

cl-quil.asd
src/ast.lisp
src/print-program.lisp

fix warning

---

src/compilers/approx.lisp

remove RANDOM from FIND-DIAGONALIZER-IN-E-BASIS

---

src/tools/circuit-diagram.lisp
src/tools/hasse-schedule.lisp
tests/tools/circuit-diagram-tests.lisp

This system looks like it was missed when the nickname was removed.

Change `quil`->`cl-quil` in `cl-quil/tools` 

---

boondoggle/src/producers.lisp
src/ast.lisp
src/build-gate.lisp
src/gates.lisp

See #873 , which I closed and split up into two PRs.

Consistency improvements

---

src/addresser/README.md

Fix typo in addresser/README.md

---

src/discrete/compilers/clifford-t.lisp
src/discrete/numeric/circle.lisp
src/discrete/numeric/cyclotomic8.lisp
src/discrete/numeric/dyadic.lisp
src/discrete/numeric/interval.lisp
src/discrete/numeric/linear-algebra.lisp
src/discrete/numeric/modulo.lisp
src/discrete/numeric/naturals.lisp
src/discrete/numeric/root2plex.lisp
src/discrete/numeric/utilities.lisp
src/discrete/operators/c2root2.lisp
src/discrete/operators/clifford.lisp
src/discrete/operators/gates1.lisp
src/discrete/operators/hadamardt.lisp
src/discrete/operators/ma-normal-form.lisp
src/discrete/operators/mat2.lisp
src/discrete/operators/pauli.lisp
src/discrete/operators/rz.lisp
src/discrete/operators/sunitary2.lisp
src/discrete/operators/unitary2.lisp
src/discrete/operators/utilities.lisp
src/discrete/package.lisp
src/discrete/rz-approx/candidate-generation.lisp
src/discrete/rz-approx/candidate-verification.lisp
src/discrete/rz-approx/generate-solution.lisp
tests/discrete/rz-approx-tests.lisp

Update the discrete compilation code to match changes in the Coalton compiler and standard library.

Fix: Coalton fixes for discrete-compilation

---

Dockerfile
README.md

Closes https://github.com/quil-lang/quilc/issues/731.

Remove references to port 6000

---

src/ast.lisp
tests/printer-test-files/gold-standard/gh-issue-908.quil

Use `format-real` when emitting a pauli sum prefactor
