quil-lang/quilc

.gitlab-ci.yml, CODEOWNERS, Dockerfile, Makefile, README.md
1. Use the new [`rigetti/rpcq`](https://hub.docker.com/r/rigetti/rpcq) image
2. Include the [`rigetti/ci`](https://github.com/rigetti/ci) docker job pipeline template rather than redefining
3. Add `README` notes about the [`rigetti/quilc`](https://hub.docker.com/r/rigetti/quilc) Docker image and how to use it
4. Add `README` notes about the release process
5. Add a `CODEOWNERS` file for default/required reviewers
=> Various improvements to the CI infra and release process

src/chip-specification.lisp, src/compilers/translators.lisp, tests/translator-tests.lisp
The translation employed here is pretty interesting. When you look at
the matrices of
```
PHASE(θ) = | 1  0   |
| 0  eⁱᶿ |
```
and
```
RZ(2α) = | e⁻ⁱᵅ  0   |
| 0     eⁱᵅ |
```
you might notice that PHASE is equivalent to RZ × e^(iθ/2). So you
seek how to write the follow gate in terms of Quil's native gates
```
RZ(β) = | eⁱᵝ  0   |
| 0    eⁱᵝ |.
```
Then it's problem solved.
Instead, remember that during measurement, any phase factor is
irrelevant! Hence PHASE ≡ RZ × e^(iθ/2) ≡ RZ.
This closes #57.
=> Compile PHASE to RZ

app/src/entry-point.lisp
[More in line now with suggestions outlined here](https://github.com/rigetti/quilc/issues/31)
Simply defined a dynamic variable holding a hash of known isa values and what they map to. There is still some conditional logic outside of that simple lookup however - just less than the original cond. A little more easily edited now perhaps.
Also looks like some white space was picked up by my config - sorry about the noise.
=> Refactoring isa descriptor selection in entry-point.lisp

app/src/printers.lisp, src/addresser/logical-schedule.lisp
Also, slightly reword the comment of LSCHEDULER-WALK-GRAPH
to clarify the explanation.
Fixes #43.
---
For example, this command
```
echo "H 0\nH 1\nCNOT 0 1" | ./quilc -P --compute-runtime
```
now prints
```
...
```
Not sure if picosecond precision is really needed, but that's what it seemed to report 🤷‍♂️
=> Show human readable time units in PRINT-PROGRAM-RUNTIME

app/src/entry-point.lisp, app/src/printers.lisp, src/matrix-operations.lisp, src/package.lisp, src/utilities.lisp, tests/compilation-tests.lisp, tests/compiler-hook-tests.lisp
I *think* the new stuff is equivalent to the old. The old stuff was
doing a lot of matrix calculations and rescaling and etc. There are
functions now that do all of this for us (gate-apps-to-log-mat,
scale-out-matrix-phases, etc)
I borrowed the matrix equality stuff from cl-quil-tests. Couple
questions,
1. Is this all equivalent?
2. Should matrix equality stuff live elsewhere (so that it's not
duplicated across quilc/cl-quil/cl-quil-tests)
3. Should that place be magicl?
Have a good weekend xxx
=> Clean up matrix printing in quilc

app/src/entry-point.lisp, app/src/rpc-server.lisp, app/src/web-server.lisp
Previously the time-limit option had no effect on the RPCQ server. Closes #124.
Some redundant/bad stuff has been removed.
Squashed commit msgs below
1. a time-limit of zero should correspond to no timeout, yet this code
leaves the default huchentoot timeout of 20s
2. in entry-point.lisp the conversion from milliseconds to seconds is
already performed, so (/ ... 1000) is unnecessary here
Specify time-limit in seconds rather than ms
And prevent negative values
Use configurable time-limit for rpcq server
Ooops - actually set time-limit
=> Respect time-limit configuration

Dockerfile, Makefile, README.md, app/src/mangle-shared-objects.lisp, build-app.lisp
Instead, use a build-app.lisp file to load quilc and save the quilc
application binary.
=> Remove use of buildapp for building

app/src/entry-point.lisp, src/chip-specification.lisp
I'm not happy with this fix, but it'll do. In the future, `build-nQ-trivalent-chip` is what ought to be repaired.
=> 16QMUX CLI option follows modern indexing conventions

src/addresser/outgoing-schedule.lisp, src/addresser/temporal-addresser.lisp, src/chip-specification.lisp, src/compilers/translators.lisp, tests/compilation-tests.lisp, tests/compiler-hook-tests.lisp
This PR changes the behavior of the `:GREEDY-QUBIT` SWAP-search strategy on CZ- or CNOT-based chips: by knowing that the compressor will eventually emit a two-qubit instruction sequence no longer than `optimal-2q` guarantees, we can elect to install a SWAP onto a recently used link, knowing that it will collapse the preceding instructions that we recently placed there.
Without this improvement, quilc decomposed `CCNOT 0 1 2` on a linear chip into a sequence of multiqubit gate depth of 11; with this it comes down to 9; and with this *and* an all-to-all CCNOT translator it comes down to 7.
Closes #80 and #84 . (#80 could be extended to cover the `:A*` search strategy too, but that looks quite complicated.)
Has a bit of a kludge in it for calculating the expected maximum duration. Improving …
=> Install SWAPs on recently used links

src/chip-specification.lisp
As written on the tin.
Looking at `chip-specification.lisp`, it might be wise to separate out all these example chips from the rest of the file.
=> Add an all-to-all chip constructor

src/chip-specification.lisp
Currently, the PHASE gate does not lend itself to parametric compilation. Since the RZ gate does, and the PHASE gate is just the RZ gate in disguise, this is a simple fix to allow programs using the PHASE gate to get parametrically compiled.
=> Compiling PHASE gate to RZ to allow for parametric compilation

src/ast.lisp
before we didn't print stuff like `3*pi/2` and now we do (because this PR goes to `2*denom` not just `denom`)
=> print more pi fractions

src/parser.lisp
Closes #103 
```
QUIL> (let ((*definitions-allowed* nil))
(parse-quil "H 0
DEFCIRCUIT TEST a b:
CNOT a b
TEST 0 1"))
```
```
At line 2: Found DEFCIRCUIT where it's not allowed.
[Condition of type QUIL-PARSE-ERROR]
```
=> Line numbers in parser errors

src/ast.lisp
Use a common superclass of unary-, binary-, and trinary-classical-instruction to share a print-instruction-generic method between them.
=> Simplify classical instruction printing

build-app.lisp, quilc.asd
There is something weird going on with build-app.lisp in Windows. My hunch is that somehow shared libraries are getting lost, but can't say more than that.
Also use `':win32` rather than `':windows` in build-app.lisp.
=> Short term fix for build-app.lisp on Windows, and use ':win32 in build-app.lisp

src/analysis/resolve-applications.lisp, src/clifford/benchmarking-procedures.lisp, src/compressor/compressor.lisp, src/compressor/wavefunctions.lisp, src/gates.lisp, src/matrix-operations.lisp, src/package.lisp, src/utilities.lisp
Closes #167. An ilog2 function has been added and all the calls to `(1- (integer-length x)` has been replace.
=> Add an ilog2 function.

src/parser.lisp
Before:
Couldn't find match at position 51 within the lexer CL-QUIL::LINE-LEXER.
After:
At line 7: unexpected input text "?" in "S? 7"
=> Nicer error message when ALEXA lexing fails on unexpected input.

app/src/entry-point.lisp, cl-quil.asd, src/ast.lisp, src/cfg.lisp, src/compilation-methods.lisp, src/matrix-operations.lisp, tests/compiler-hook-tests.lisp, tests/typed-memory-tests.lisp
quilc emits the state of the logical-to-physical assignment of qubits at the start and finish of each block of the CFG. Currently, this information is shared through PRAGMAs, which is a misuse: the PRAGMA directives have no content from the compiler's perspective, and _comments_ are what we're supposed to use to encode things that only have information from a _user_'s perspective. This PR enacts this migration.
Lingering TODOs:
=> Rewiring comments

app/tests/faithfulness-tests.lisp
I am new to Quil and quilc, but I am trying to learn by poking quilc with a stick. I noticed these tests weren't running, so I took a stab at fixing them. But I am unsure about points 4) and 5), below. Feedback welcomed.
Test output prior to this fix:
```
QUILC-TESTS (Suite)
TEST-FAITHFULNESS.......................................................[ OK ]
TEST-EASY-VERSION-CALL..................................................[ OK ]
TEST-QUIL-ROUNDTRIP.....................................................[ OK ]
```
After the fix:
```
QUILC-TESTS (Suite)
Testing file CCNOTs
Testing file johannes
Testing file some-CZs
TEST-FAITHFULNESS.......................................................[ OK ]
TEST-EASY-VERSION-CALL..................................................[ OK ] …
```
=> Fixes for test-faithfulness in quilc-tests

app/src/entry-point.lisp
This PR fixes a bad interaction between #159 and #189.
Closes #199, fixes the build failure in #197 (and probably also #190). H/t to @appleby for both spotting the error and correctly guessing the solution.
=> preserve the 'Exiting rewiring' comment when deleting the HALT instruction on a protoquil program

src/ast.lisp, src/compressor/compressor.lisp, src/package.lisp
This also changes some (current 1) call site of PRINT-INSTRUCTION to use the new format directive.
This addresses #116.
=> add INSTRUCTION-FMT for FORMATting instructions

app/src/rpc-server.lisp
When https://github.com/rigetti/rpcq/pull/45 gets merged, we will need to update some of the unpacking done in the quilc RPCQ server. This PR handles that change.
=> RPCQ changed from de/serializing lists to de/serializing vectors

.gitignore, README.md, app/src/entry-point.lisp, app/tests/faithfulness-tests.lisp, app/tests/rpcq-tests.lisp, src/compressor/compressor-configuration.lisp, src/matrix-operations.lisp, tests/benchmarking-procedures-tests.lisp, tests/compilation-tests.lisp, tests/compiler-hook-tests.lisp, tests/utilities.lisp
This PR contains miscellaneous fixes for typos, stale comments, minor refactorings and the like that caught my eye while reading over the code. The commits are independent and unrelated, but it seemed liked overkill to create separate pull requests for each, so I rolled them all up into one. If you prefer separate PRs, just say the word.
Individual commit messages copied/pasted here for easier perusal.
- Call `quilc::%entry-point` from `quil::entry-point`
This removes a tiny bit of code duplication and makes it clear that `entry-point` and `%entry-point` are equivalent, modulo debugger setup and error reporting.
- Remove duplicate code from tests/utilities.lisp
Copies of `matrix-equals-dwim`, `operator=`, and `first-column-operator=` appear in `cl-quil-tests` and `cl-quil`. Remove the …
=> Miscellaneous trivial fixes

src/cfg.lisp, src/compressor/compressor.lisp
User-reported errors seem to cleave into two sorts:
1. There's only one place such an error message could be triggered, and with a bit of effort you can dream up some bad input that will indeed cause the error.
2. The error message is completely opaque, and the triggering of the error appears to be extremely sensitive to the precise user input.
Errors of type 2 seem to be partially localized: they rarely happen in the addresser, and they rarely (so far: never!) happen in the 'logic' of the compressor. Instead, they always happen deep in the guts of the compressor and require knowledge about which straight-line sequence was fed in to be processed.
This PR adds a `handler-case` that dumps relevant information to `stderr` in the event of such a crash. I don't really know what Best Practices …
=> Print debug info during compression errors

src/analysis/process-includes.lisp
I think this was originally optional, but at somepoint was changed?
This is causing a bug in QVM, where the patch-labels transform depends
on the process-includes transform, but doesn't provide an originating
file. Should it?
=> Make originating-file optional

src/matrix-operations.lisp, tests/compiler-hook-tests.lisp
While gazing at these lovely codes I noticed that in `quil::parsed-program-to-logical-matrix`, when there is a combined entering/exiting rewiring on a single instruction, it calls the locally-defined function `apply-entering-rewiring` on the `exiting-vector` and `apply-exiting-rewiring` on the `entering-vector`. This seemed backwards to me, but I am noob and lack understanding.
Is this a bug? Expected?
I wrote a test that I think indicates a bug, but I might be holding it wrong. Prior to these changes, the new test fails like so (after, all tests pass):
``` common-lisp
CL-USER> (fiasco:run-tests 'cl-quil-tests::test-parsed-program-to-logical-matrix-entering-exiting-rewiring)
TEST-PARSED-PROGRAM-TO-LOGICAL-MATRIX-ENTERING-EXITING-REWIRING...........[FAIL]
Test run had 1 failure:
Failure 1: …
```
=> Question about rewirings in parsed-program-to-logical-matrix

cl-quil.asd, src/analysis/resolve-applications.lisp, src/ast.lisp, src/compilers/approx.lisp, src/compilers/optimal-2q.lisp, src/gates.lisp, src/operator-bind.lisp, src/package.lisp, src/quil/README.txt, src/quil/stdgates.quil
This commit does a good helping of refactoring, further clarifying
confusion over what a gate is, how a standard gate rears its head, and
how CONTROLLED and DAGGER gates get simplified.
Three big notable things in this PR:
- Standard gates are read from a new file src/quil/stdgates.quil.
- GATE-APPLICATION-GATE is not an accessor anymore, but a function
that computes and caches a gate object depending on the resolved
name.
- Hooks to optimize the representation of a CONTROLLED gate and a
DAGGER gate exist with the generic functions CONTROL-GATE and
DAGGER-GATE, which are to be read as verbs.
This is intended to replace PR #217, and should **NOT** be merged only until @notmgsk's PR #150 is merged. (The reason to wait is because all of the standard gates are being boiled away to their Quil …
=> treat stdgates uniformly with other DEFGATES (and more)

app/src/entry-point.lisp
This is declared as `(:list :integer)` in the RPCQ spec, but quilc was putting the unevaluated `:string` into the slot instead.
(cf. https://rigetti-forest.slack.com/archives/C77UQCY57/p1557087073119200 )
=> fix type of 'final_rewiring' in quil_to_native_quil response

.gitignore, Makefile, cl-quil.asd, src/contrib/tweedledum/tweedledum.lisp
Fixes #221
- Free the foreign string returned by `tweedledum_synthesis_dbs`
- Add `*.so` and `*.dylib` to .gitignore
- Add `test-tweedledum` target to Makefile
- Remove shared objects in `src/contrib/**` during make clean
=> Free the foreign string returned by tweedledum_synthesis_dbs

app/src/versions.lisp, app/tests/misc-tests.lisp, app/tests/utils.lisp, quilc-tests.asd
Previously, we said "1.2.0" was newer than "1.1.0" because we relied
on string= for kinda valid reasons.
=> Saner version checking

Dockerfile, README.md
Fixes #213.
Also adds the docker pulls badge to the README, which shows 4k pulls! :)
=>  EXPOSE the default quilc server ports in the Dockerfile

app/src/entry-point.lisp, app/tests/faithfulness-tests.lisp
Replace most global state mutation in quilc with let bindings.
This is "option 5" from the discussion in #192. Turns out the state mutation was almost entirely confined to `quilc::process-options`, so switching to let bindings everywhere wasn't too bad.
The only remaining global state mutation occurs in `quilc::setup-debugger` which is called from `quilc::entry-point`, but not `quilc::%entry-point`. Removing this last bit of state mutation is also possible, but slightly uglier since it requires either peeking under the covers of `sb-ext:disable-debugger` to figure out what additional vars to let-bind, or else running the body of `quilc::entry-point` in an `unwind-protect` that calls `quilc::enable-debugger` on exit. Since the whole point of `quilc::%entry-point` is presumably to provide a …
=> Reduce global state mutation in quilc

src/ast.lisp, src/clifford/benchmarking-procedures.lisp, src/gates.lisp, src/parser.lisp, src/utilities.lisp, tests/misc-tests.lisp
I am not sure if this fix is semantically correct, but it fixed `make test` in the qvm repo :).
Note that there exists a wrapper function `cl-quil:make-permutation-gate`. As far as I can tell it's not used anywhere, but in theory the handful of individual calls to `(make-instance 'permutation-gate ...)` could be replaced with calls to `make-permutation-gate`, which handles setting `:dimension` for you.
Fixes rigetti/qvm#85
=> Move the DIMENSION slot from the GATE abstract base class into the PARAMETERIZED-GATE class

src/clifford/stabilizer.lisp, src/utilities.lisp, tests/misc-tests.lisp
POWER-OF-TWO-P was renamed in de7367c72b23a236ef16e37d2fa8218ac3396119, which was merged shortly after this code.
I am not sure how to test this function (see #236), but can confirm I no longer get a style-warning when compiling.
=> Add POWER-OF-TWO-P and call it in CLIFFORD-STABILIZER-ACTION

app/src/versions.lisp, src/clifford/god-table.lisp
- Don't define unused `TIME` variable in god-table.lisp
- Forward-declare `quilc::*logger*` in versions.lisp
=> Quash compiler warnings

src/cfg.lisp, tests/cfg-tests.lisp
When processing a JUMP-UNLESS or JUMP-WHEN instruction, PROCESS-INSTRUCTION will return a non-nil LINK-SUCCESSOR?, requesting the just-finished block to be linked to it's successor. Previously, if the conditional jump instruction was the final instruction in the program, successor linkage would not happen and the finished block's OUTGOING slot would be unbound. The compiler would later choke on said block, resulting in an UNBOUND-SLOT error.
With this change, ensure that successor linkage always happens, if requested, after PROCESS-INSTRUCTION returns.
Additionally, fix PRINT-OBJECT and the various routines for generating graphviz output to check for SLOT-BOUNDP before attempting to access the block's OUTGOING slot.
Fixes #244
Note that this commit only focuses on fixing the …
=> Respect final instrucion's wish to LINK-SUCCESSOR? in PROGRAM-CFG

src/clifford/god-table.lisp
Fix a straggler that I missed in #252.
- Don't define unused NUM-CLIFFORDS in god-table.lisp
=> Quash another compiler warning

app/src/entry-point.lisp
Produces a name like `"<A>...<B>"` where `<A>` is a 15-char chunk from the
beginning of the name, and `<B>` is a 30-char chunk from the end of the
name.
=> Clamp *program-name* to 48 chars

app/tests/package.lisp, benchmarking/package.lisp, benchmarking/rewiring-analysis.lisp, src/addresser/cost-function.lisp, src/addresser/initial-rewiring.lisp, src/addresser/outgoing-schedule.lisp, src/analysis/rewrite-arithmetic.lisp, src/ast.lisp, src/clifford/clifford.lisp, src/clifford/god-table.lisp, src/compressor/compressor.lisp, src/package.lisp, src/parser.lisp, src/resource.lisp, src/utilities.lisp, tests/misc-tests.lisp, tests/package.lisp
With these commits cl-quil loads without problems on ECL[1]. Some fixes are made to improve CCL support, but it still doesn't load cl-quil because of how ADT creates structuers (it uses uninterned symbols and make-load-form-saving-slots on CCL doesn't use slot offsets but names).
[1] Branch is not merged yet, but it introduces improvements to make-load-form-saving-slots and adds custom equivalence predicate capabilities to make-hash-table.
https://gitlab.com/embeddable-common-lisp/ecl/merge_requests/152
=> Portability improvements

src/compilation-methods.lisp
Refactor OUTER-INSTRUCTION-LOOP in ALGEBRAICALLY-REDUCE-INSTRUCTIONS and EXHAUST-STACK in COMPILATION-HOOK from tail-recursive calls to explicit LOOPs.
I started working on this to try and get the test suite passing on ECL. However, it looks like there might be more places that need converting (e.g. OPTIMAL-2Q-COMPILER, EXPAND-TO-NATIVE-INSTRUCTIONS, possibly others) so I'm posting here to see if folks want to try and continue down this path of selectively converting tail-recursive functions into LOOPs wherever possible, or if we want to try another tack. If there are only a handful of these tail-recursive functions and this seems like a reasonable approach, then I can try refactoring EXPAND-TO-NATIVE-INSTRUCTIONS next. On the other hand, if we expect there are many such tail-recursive …
=> Convert EXHAUST-STACK in COMPILATION-HOOK from tail-recursion to an explicit LOOP

src/analysis/rewrite-arithmetic.lisp
Previously this would error if `isn` was anything but an `instruction` or `application`. This closes #266.
=> rewrite-arithmetic-for-isn matches all quil types

src/addresser/logical-schedule.lisp, src/compressor/compressor.lisp
Functions in question are: walk-graph-with-candidates, outer-instruction-loop and expand-to-native-instructions.
Feel free to close the PR if you find recursion more elegant and it is not that much of a problem. With these changes sbcl passes tests on low speed / high safety and debug settings. I haven't encountered stack overflow on ECL so far either (but tests still run).
=> replace recursion in functions with iteration

src/clifford/benchmarking-procedures.lisp
I assume this code was written before pragmas etc were introduced. Executable
code now contains non-application stuff (pragmas) and so must be careful with
types.
Fixes rigetti/pyquil#858.
=> Fix type checking of instructions in clifford stuff

src/compilation-methods.lisp, src/compilers/approx.lisp, src/compilers/optimal-2q.lisp, src/compressor/rewriting-rule-data-type.lisp, src/compressor/rewriting-rules.lisp
Updates relevant call sites previously using the non-specific `GIVE-UP-COMPILATION` to directly signal the new condition when applicable. 
please see rigetti/quilc/issues/46
=> Adds compiler-rewrite-does-not-apply error condition

tests/misc-tests.lisp
This test was moved into printer-tests.lisp and renamed to TEST-INSTRUCTION-FMT in #257.
It also got a similar refactoring (without moving files) in #263, and hence wound up in both places, presumably in a merge-conflict gone awry.
Relevent PR threads [here](https://github.com/rigetti/quilc/pull/257#discussion_r288248321) and [there](https://github.com/rigetti/quilc/pull/263#discussion_r291385988).
=> Remove duplicate TEST-PRINT-INSTRUCTION

src/ast.lisp, tests/parser-tests.lisp, tests/printer-tests.lisp
- Drop singleton metaclass for the above instructions
- Remove RESET-COMMENT-TABLE-HACK, which is no longer needed.
- Update a parser test that broke as a result of this change.
Fixes #270
The self-flagellating feature expressions are to serve as a reminder that, in a better world, referential transparency would be preserved.
=> Remove singleton metaclass for NOP, HALT, RESET, and WAIT

app/src/rpc-server.lisp, app/src/web-server.lisp, app/tests/rpcq-tests.lisp, quilc-tests.asd, src/package.lisp
quilc endpoints are mostly untested, which allowed a bug to creep in (see #287).
The tests here could be better, if I knew more about cliffords etc.
=> Test quilc endpoints

Makefile, app/src/entry-point.lisp, src/contrib/tweedledum/README.md, src/contrib/tweedledum/tweedledum.lisp
This is a simple way to fix the issue. Its drawback is that it requires that the user fiddles with LD_LIBRARY_PATH.
I tried different alternatives such as [1] `setf`-ing `(uiop:getenv "LD_LIBRARY_PATH")` from within the method `perform ((operation load-op) (component c->so))` and [2] trying to remove the hardcoded path from `sb-sys:*shared-objects*` before calling `save-lisp-and-die`, but this was the cleanest fix.
I've tested this patch using make test-tweedledum.
=> Rely on the dynamic linker for libtweedledum (#254)

src/compilers/cs-compile.lisp, src/compilers/ucr-explode.lisp
=> Ignore some pedagogical code that may refer to retired symbols

src/clifford/benchmarking-procedures.lisp, tests/benchmarking-procedures-tests.lisp
Eliminated errors from `phase-to-string` and `string-to-phase` so that the test suite could continue and reject invalid pauli matrices on its own, and changed the qubit ordering convention in `test-clifford-from-quil` to be consistent with the clifford/paulis' new computational basis argument convention.
Fixes #299
=> fixing tests to adhere to previous PR for fix/clifford_ket

cl-quil.asd
`g++` seems like a more reasonable default
=> clang++-7 -> g++

boondoggle/src/package.lisp
Boondoggle refers to "alexandria" as "a", but the local nickname was not set up.
=> Boondoggle package-local nickname for alexandria

Dockerfile
The new default `g++` is not available in the docker builds, or at least it is too old. The docker builds do have `clang++-7` however, so configure them to use that.
=> Configure docker env var for CXX

src/parser.lisp, tests/printer-test-files/gold-standard/plundered-gold.quil
This a manual revert of the last commit from #316.
For context: https://github.com/rigetti/quilc/pull/316#discussion_r301745558
=> Revert changes to gate modifier parsing

src/compressor/compressor.lisp, tests/compiler-hook-tests.lisp
Working on a compilation subroutine and you aren't sure how it's affecting output quality for example programs? Try running `cl-quil-tests::test-compiler-hook` with `print-stats` turned on!
=> Publish test-compiler-hook stats

src/chip-reader.lisp, src/chip-specification.lisp, src/types.lisp, tests/misc-tests.lisp
This PR defends against 3 kinds of malformed input:
* Forest DB has taken to assigning a fidelity of -1 when the backend determines that a qubit has such low gate fidelity that it isn't worth estimating. This is no bueno; we reset this is `+near-perfect-fidelity+` for lack of a real floor.
* Various lazy actors have been supply quilc with various malformed qubit keys in their ISA / specs payloads. We now deliberately consume all of them and convert them to something uniform internally.
* The problem that motivated this PR: under/over-specificity when trying to match `gate-binding`s could cause `specs` entries to get skipped. These are now more robustly treated.
=> fix: read 1Q specs correctly

src/analysis/process-includes.lisp, tests/parser-tests.lisp
This addresses #91. When a memory region is declared across multiple files, this signals a `quil-parse-error`.
=> Include memory definitions from included quil

src/addresser/astar-rewiring-search.lisp, src/addresser/logical-schedule.lisp, src/addresser/temporal-addresser.lisp, src/compilation-methods.lisp
This is a stab at #51, in part for my own edification. 
Basically I split `DO-GREEDY-TEMPORAL-ADDRESSING` into toplevel defuns. The previous shared state in `DO-GREEDY-TEMPORAL-ADDRESSING` is now bundled together in a parameter, `*temporal-addresser-state-variables*`, which contains the active `temporal-addresser` that is being worked on.  I've made a few small tweaks to the code, cleaning up various parts, as well as added additional documentation.
This isn't really changing any behavior. I'm open to additional improvements or alterations as seen fit.
=> DO-GREEDY-TEMPORAL-ADDRESSING is too big to fail

src/parser.lisp, tests/lexer-tests.lisp, tests/parser-tests.lisp
Here's a proposal for #386, allowing for `:SEMICOLON` tokens early on which get removed at the same time as `:NEWLINE` tokens. Tokens still retain their line numbers relativ to `:NEWLINE` tokens.
=> add semicolons to parser

Makefile, app/src/entry-point.lisp, app/tests/misc-tests.lisp, app/tests/rpcq-tests.lisp, build-app.lisp, quilc-tests.asd, quilc.asd
Fix a bug in `SPECIAL-BINDINGS-LET*` that was causing quilc to crash if the user specified either the `--gate-whitelist` or `--gate-blacklist` options in combination with `-S` or `-P`.
Also:
- use `SPECIAL-BINDINGS-LET*` in `TEST-QUIL-TO-NATIVE-QUIL-ENDPOINT-OVERRIDES-SERVER` rather than `SETF`.
- Remove last traces of hunchentoot from Makefile, build-app.lisp, and quilc.asd.
Copy/paste of commit message:
**Fix a bug in `SPECIAL-BINDINGS-LET*`**
`SPECIAL-BINDINGS-LET*` needs to expand to a form that quotes the value being added to `BT:*DEFAULT-SPECIAL-BINDINGS*`; otherwise, binding non-self-evaluating forms will cause an error once a new thread is created.
In other words, we want to expand to something like:
```
CL-USER> (macroexpand '(quilc::special-bindings-let* ((*foo* 'foo))))
(LET* …
```
=> Fix SPECIAL-BINDINGS-LET*

.gitlab-ci.yml, Dockerfile, README.md
=> Rework the Docker inheritance and CI pipeline

app/src/rpc-server.lisp, src/analysis/compress-qubits.lisp, src/analysis/expand-circuits.lisp, src/analysis/fusion.lisp, src/analysis/patch-labels.lisp, src/analysis/process-includes.lisp, src/analysis/resolve-applications.lisp, src/analysis/rewrite-arithmetic.lisp, src/ast.lisp, src/cfg.lisp, src/cl-quil.lisp, src/classical-memory.lisp, src/compilation-methods.lisp, src/gates.lisp, src/matrix-operations.lisp, src/parser.lisp, tests/cfg-tests.lisp, tests/compiler-hook-tests.lisp, tests/misc-tests.lisp, tests/parser-tests.lisp, tests/printer-tests.lisp, tests/state-prep-tests.lisp, tests/typed-memory-tests.lisp
Previously `PARSE-QUIL-INTO-RAW-PROGRAM` produced a `PARSED-PROGRAM` object, which in particular had no notion of where or in what order its various definitions originated. This is fine if the presence of multiple conflicting definitions results in undefined behavior, but e.g. it might be nice to have the option for more fine-grained control in name resolution. Further, the quilt proposal allows (and even encourages) multiple calibrations for a given gate, and we need to be able to support that adequately. After discussions with @ecpeterson and @stylewarning I've opted to shuffle things around a bit.
This PR changes `PARSE-QUIL-INTO-RAW-PROGRAM` to produce a list of ast objects in their source order. `PROCESS-INCLUDES` and `RESOLVE-APPLICATIONS` have been downgraded to ordinary functions …
=> Rethink 'Raw' Quil

README.md
- HTTP server mode was recently deleted. Remove the README sections that mention it.
- Update examples that include `echo` commands to pass unquoted arguments, and remove the Windows-specific note.
=> Remove README references to the now-deleted HTTP server mode

build-app.lisp
Disable `zap-info` in build-app.lisp on SBCL 1.5.6+.
This is similar to work-around in https://github.com/rigetti/qvm/issues/172, but limited to SBCL versions >= 1.5.6.
Updates #401 
~~Build is now working, but test suite still fails with memory corruption error.~~
The non-zap-info-related memory corruption issues mentioned in #401 were resolved by the following SBCL commit:
https://sourceforge.net/p/sbcl/sbcl/ci/550c4d23c77cc670fb95d7216e3c6d493bbd76eb/
All tests (including qvm and pyquil tests) are now passing locally when built with SBCL master with the above fix.
=> Disable ZAP-INFO on SBCL 1.5.6+

src/chip-specification.lisp, src/compilers/state-prep.lisp, src/matrix-operations.lisp, tests/state-prep-tests.lisp
This implements the 4q state prep method mentioned in https://github.com/rigetti/quilc/issues/76.
It also updates the test that https://github.com/rigetti/magicl/pull/58 breaks.
=> 4q state prep

app/src/entry-point.lisp, build-app.lisp
Moves the tweedledum load call into `build-app.lisp`.
=> Fix startup spam

src/ast.lisp, src/cfg.lisp
Fixes a bug introduced in #375 which resulted in the final exit rewiring comment sometimes getting pretty-printed.
This bug is a gentle reminder that the changes suggested in #381 would not be in vain.
Fixes #414
=> Set *PRINT-PRETTY* to NIL in MAKE-REWIRING-COMMENT

README.md
Not 100% sure why the build badge isn't rendering -- this might do the trick.
=> Fix GitLab CI pipeline badge in README

app/src/entry-point.lisp, build-app.lisp, src/contrib/tweedledum/tweedledum.lisp
I previously (#409) tried to clear up the quilc start-up warning spam that was introduced in #276, but that introduced a second issue (in the barebones distribution, the library would not be found).
So this PR covers two things:
* Muffle the warnings that happen at quilc startup. I'm still not sure what is causing these, but they're AFAICT harmless warnings that we can ignore.
* Add more paths to the list of paths that CFFI searches for libraries (this removes the requirement of modifying `LD_LIBRARY_PATH` to pick up the library in the current dir: e.g. `LD_LIBRARY_PATH=./ quilc`).
=> Muffle start up warnings, and search more paths for libtweedledum.so

src/parser.lisp, tests/bad-test-files/bad-load-store.quil, tests/good-test-files/good-classical-binaries.quil, tests/good-test-files/good-classical-load-store.quil, tests/printer-test-files/gold-standard/classical.quil, tests/printer-test-files/gold-standard/plundered-gold.quil
According to the Quil spec, `STORE`'s second argument must be a reference to an int, and its third argument can be either a memory reference or an immediate value.
Fixes #425
=> Update parsing of STORE instruction to conform to Quil spec

src/compilers/approx.lisp, src/compilers/state-prep.lisp, tests/state-prep-tests.lisp
A long while back, Oscar Perdomo provided us with some formulas to perform exact state-to-state transformations between two-qubit systems. This PR implements his techniques.
TODO:
=> Exact 2Q state preparation

Makefile
Closes #443 (see for more details).
=> Remove unnecessary testing repo from Makefile

src/addresser/logical-schedule.lisp, src/addresser/rewiring.lisp, src/analysis/expand-circuits.lisp, src/analysis/resolve-applications.lisp, src/analysis/type-safety.lisp, src/ast.lisp, src/cfg.lisp, src/chip-reader.lisp, src/compilers/state-prep.lisp
People have expressed a preference for using `instruction-fmt` for printing AST objects, as opposed to e.g. `(print-instruction obj nil)` which allocates a string and relies on a method specialized on the null class. I'm just applying this uniformly here. This is a spillover from the quilt PR, since that is already too large.
=> Prefer format string for printing AST objects

src/addresser/initial-rewiring.lisp, src/addresser/outgoing-schedule.lisp, src/addresser/path-heuristic.lisp, src/addresser/rewiring.lisp, src/addresser/temporal-addresser.lisp, src/analysis/resolve-applications.lisp, src/analysis/type-safety.lisp, src/ast.lisp, src/clifford/clifford.lisp, src/clifford/god-table.lisp, src/clifford/pauli.lisp, src/define-compiler.lisp, src/define-pragma.lisp, src/parser.lisp, src/transformable-mixin.lisp
There seem to be three general options at the end of a sentence: a question mark, an exclamation mark, or a period. This PR adopts the latter as the "default" option in several error messages and docstrings. I doubt that we have 100% coverage here, but that's just how it goes.
In the process of adding periods, I spotted some questionable multi-line docstrings. I will leave these for a later PR.
=> add periods to sentences without periods

tests/printer-tests.lisp, tests/utilities.lisp
And submit to the no-newlines-in-docstrings convention 😞.
Also, capitalize "pairs" in section heading of the golden files comment in utilities.lisp.
=> Fix docstring typos for UPDATE-PRINT-PARSED-PROGRAM-GOLDEN-FILES

tests/qpu-test-files/update_aspen_qpu_files.py
The latest e.g. Aspen-4 chip will be available under ./tests/qpu-test-files/Aspen-4/latest (symlinked appropriately).
=> Pull latest Aspen devices into structured dirs

app/src/entry-point.lisp
As is done in QVM. Could alternatively sanitise the name, but that's more work for little gain.
=> Use "quilc" rather than argv[0] for syslog name

src/chip/chip-reader.lisp, src/chip/chip-specification.lisp, src/compressor/compressor.lisp, src/define-compiler.lisp
Adds support for an ISA operator field to be specified as `"_"`, which permits the consumption of any gate. This leads to addresser behavior like:
```
(let ((chip (qpu-hash-table-to-chip-specification
(yason:parse "
{\"isa\":
{\"1Q\":
{\"0\":
{\"gates\": [{\"operator\": \"_\", \"parameters\": \"_\", \"arguments\": [\"_\"]}]},
\"1\":
{\"gates\": [{\"operator\": \"_\", \"parameters\": \"_\", \"arguments\": [\"_\"]}]},
\"2\":
{\"gates\": [{\"operator\": \"_\", \"parameters\": \"_\", \"arguments\": [\"_\"]}]}},
\"2Q\":
{\"0-1\":
{\"gates\": [{\"operator\": \"_\", \"parameters\": \"_\", \"arguments\": [\"_\", \"_\"]}]},
\"1-2\":
{\"gates\": [{\"operator\": \"_\", \"parameters\": \"_\", \"arguments\": [\"_\", \"_\"]}]},
}}}"))))
(print-parsed-program
(compiler-hook (parse-quil "
CZ 0 1
CZ 1 2 …
```
=> wildcard ISAs

src/build-gate.lisp, src/compilers/approx.lisp, src/define-compiler.lisp, src/package.lisp
We export a few internal functions so that building Quil can be an easier affair.
This also changes the syntax of WITH-INST ever so slightly to allow future extensions and stuff.
=> expose WITH-INST and friends

app/src/entry-point.lisp, app/src/versions.lisp, app/tests/faithfulness-tests.lisp, app/tests/misc-tests.lisp
This will start a thread to check the version to avoid having a delay for the network request. It will report to the log what's going on.
=> asynchronously check for version update

cl-quil-tests.asd, src/analysis/simplify-arithmetic.lisp, src/build-gate.lisp, src/cl-quil.lisp, src/compilation-methods.lisp, src/compressor/rewriting-rules.lisp, tests/rewrite-tests.lisp
Closes #468.
Previously, an instruction sequence involving named parameters that might reasonably be reduced (e.g. `RZ(theta[0] - theta[0])`) would be missed by the compiler.  @karalekas introduced the `simplify-arithmetic` routine (#211) that is capable of reducing that type of parameter, but it was not installed as part of the compilation pipeline.
This PR uses some of the functionality introduced in #211 (namely `canonicalize-expression`) to simplify arithmetic expressions that involve named (delayed) parameters.
Old:
```
QUIL> (print-parsed-program
(compiler-hook (parse-quil "DECLARE theta REAL[1]; RZ(theta) 0; RZ(-theta) 0;")
(build-nq-fully-connected-chip 2)))
DECLARE theta REAL
RZ((theta[0]+-(theta[0]))) 0            # Entering rewiring: #(0 1)
HALT …
```
=> Fix parametric RZ agglutination

src/analysis/type-safety.lisp, src/ast.lisp, tests/typed-memory-tests.lisp
The type requirements in [the spec](https://github.com/rigetti/quil/blob/master/rfcs/typed-memory.md#classical-instructions) were not re**spec**ted.
=> Fix type checking for classical-equality instructions

src/quilt/ast.lisp, src/quilt/parser.lisp, tests/quilt/bad-test-files/bad-quilt-defframe-direction.quil, tests/quilt/good-test-files/good-quilt-defframe.quil, tests/quilt/parser-tests.lisp
This is related to https://github.com/rigetti/quil/pull/37
Basically, we let frame directions be explicitly annotated in Quilt source, rather than implicitly floating around inside (whatever machine is responsible for compiling this).
=> Add DIRECTION as frame attribute

app/src/entry-point.lisp, app/src/rpc-server.lisp, app/tests/rpcq-tests.lisp, src/analysis/process-includes.lisp, src/package.lisp, src/parser.lisp
For the sake of security, `SAFELY-PARSE-QUIL` restricts the `INCLUDE` command to only accept paths relative to the value of `*safe-include-directory*`.
=> Use SAFELY-PARSE-QUIL on external input

src/cl-quil.lisp, tests/qasm-tests.lisp
Previously this would infini-loop when given an empty string.
=> Ensure %CHECK-FOR-QASM-HEADER works when given an empty string

src/qasm.lisp, tests/qasm-tests.lisp
This caused the compiler to try to enter the debugger when parsing a direct `U`-gate application in program like so:
```
OPENQASM 2.0
qreg q[1]
U(0,0,0) q[0]
```
=> Remove stray (BREAK) when parsing U-gate application in qasm.lisp

app/src/entry-point.lisp, app/tests/misc-tests.lisp
Take @ecpeterson's sage advice from #375 and refactor `%STRIP-HALTS-RESPECTING-REWIRINGS` to only deal with a single HALT instruction at the end of the program, rather than stripping HALTs anywhere in the program. For starters, as [ecp mentions in the comment thread](https://github.com/rigetti/quilc/pull/375#discussion_r311787805) of #375, this function is only called in protoquil mode, so there should only be one HALT at the end. Even if there were multiple HALTs, stripping away a mid-program HALT is not likely to leave you with an equivalent program, so it doesn't seem very useful to support that, even in theory.
As noted in the original thread, this refactoring actually makes the code slightly longer and doesn't really improve big-O complexity since we still need to copy the vector to …
=> Refactor %STRIP-HALTS-RESPECTING-REWIRINGS

src/addresser/addresser-common.lisp, src/addresser/fidelity-addresser.lisp, src/addresser/rewiring.lisp, src/compilers/translators.lisp, tests/compilation-tests.lisp
`cost-function` expands its input instruction into a list of native instructions. If the instruction is not first rewired, then `expand-to-native-instructions` will get confused and infiniloop. For example, if a chip has live physical qubits 3 and 4, then the instruction `CZ 0 1` will be expanded into `CAN ... 0 1` will be expanded into `CZ 0 1` will be expanded into `CAN ... 0 1` ... etc.
My first thought was that `expand-to-native-instructions` should be aware of the current rewiring by providing it a `addresser-state` object containing the rewiring, or even just the rewiring itself. Until now, however, that hasn't been required and so maybe isn't the best solution.
Second (and current) solution, is to temporarily apply the current rewiring to the instruction in `cost-function` (being …
=> Rewire INSTR before EXPAND-TO-NATIVE-INSTRUCTIONS in COST-FUNCTION

elf-library/.gitignore
Ignore the build artifacts produced by the `elf-library/Makefile`.
Not that anyone ever builds these things, but just in case...
=> Add .gitignore file to the elf-library directory

src/chip/chip-specification.lisp, src/define-compiler.lisp
Closes #404 , leading to pleasant output like:
```
QUIL> (compiler-output-gates #'euler-zyz-compiler)
RZ (_) _ -> 2
RY (_) _ -> 1
```
A thought: should `gateset`s also be first-class types?
=> wrap occurrence tables in a struct

src/build-gate.lisp, src/parser.lisp, tests/translator-tests.lisp
This PR adds support for manually specifying compiler fuzzers for use during `test-translators`. The fuzzers this includes brings the automatic testing from ~50% to ~70% of all compilers.
Two things left undone, which are each beyond the scope of this PR:
* I haven't written fuzzers for the state preparation routines. Some of these depend on knowing a wavefunction context, which isn't readily available; and some of these depend on the tester knowing to use a particular sort of matrix equality check, which it's currently ignorant of.
* I haven't written fuzzers for the guarded compilers whose only guard is "someone's qubits need to subsume someone else's qubits". This is a common enough pattern that we should augment the automated fuzzer to handle this case.
A separate concerning thing:
* …
=> add manually-specified fuzzers

benchmarking/qasm-benchmarks.lisp, cl-quil-benchmarking.asd
This commit:
* Prints the timed out benchmarks at the end in Lisp-readable form
* uses TG:GC instead of SBCL internals
* abridges length and depth of configuration printing
* doesn't include GC and file slurpage in timeout
=> make QASM benchmark code prettier

src/parser.lisp, tests/translator-tests.lisp
cf. https://github.com/rigetti/quilc/pull/498#pullrequestreview-334160910
=> Add some more tests for DEFEXPI functionality

src/analysis/type-safety.lisp, tests/typed-memory-tests.lisp
The spec says that all STOREs should permit an immediate integer type
as the value operand. Prior to this, the following (legal) Quil would
fail:
DECLARE ro REAL
DECLARE index INTEGER
STORE ro index 1
where instead one would have to write
DECLARE ro REAL
DECLARE index INTEGER
DECLARE val REAL
MOVE val 1
STORE ro index val
=> Allow immediate integers for all STORE values

src/parser.lisp
During parsing some memory references are not validated. I'm inclined to think that the function `parse-memory-or-formal-token` should have a default `t` for  the kwarg `ensure-valid`. Unless there was a reason it is `nil` by default?
=> Ensure valid memory refs in classical instructions

src/addresser/embed-swap.lisp, src/addresser/fidelity-addresser.lisp, src/addresser/rewiring.lisp, src/addresser/temporal-addresser.lisp
`cost-function` expects the input instruction to be logically addressed, and it will perform the mapping in the current rewiring before handing the instruction off to `expand-to-native-instructions`.
=> Provide logically addressed instr to COST-FUNCTION

src/addresser/astar-rewiring-search.lisp, src/resource.lisp
Be more tolerant of IMPOSSIBLY-FULL-RESOURCEs in RESOURCE-DIFFERENCE and RESOURCE-SUBSETP. Previously, if RESOURCE-DIFFERENCE was given an IMPOSSIBLY-FULL-RESOURCE as it's first argument, it would signal RESOURCE-COLLECTION-UNBOUNDED-NAMES. Now it only does so if the second argument is not also "impossibly full".
RESOURCE-SUBSETP now explicitly checks for impossibly full resources, and only delegates to RESOURCE-DIFFERENCE in cases where it is guaranteed safe and returns NIL otherwise.
Closes #346
=> Be more tolerant of IMPOSSIBLY-FULL-RESOURCEs

src/compilers/translators.lisp
In leui of a more complex and generic compilation method, here we have a simple XY->CZ translator.
=> Basic XY-to-CZ compiler

app/src/entry-point.lisp
Ditto. Prevent `--print-statistics` from being our best (worst?) kept secret.
=> Actually show print-statistics in help message.

src/chip/chip-reader.lisp
Purely for ease-of-use, shouldn't affect end-users.
=> Allow XY in deprecated ISA gates field

src/define-compiler.lisp
This is what was originally intended, but wasn't actually mutating the compiler list.
=> Allow on-the-fly redefinitions of compilers

Makefile, build-app.lisp
This prevents the annoying situation where you've loaded e.g. drakma in your REPL with SSL enabled, and after that when you try to compile quilc you get the error about being unable to find the CL+SSL package.
=> Only disallow SSL for SDK builds

src/quilt/ast.lisp, src/quilt/parser.lisp, src/quilt/waveform.lisp, tests/quilt/good-test-files/good-quilt-measure-calibration.quil, tests/quilt/parser-tests.lisp
These changes updates that are already recorded in the Quilt spec (https://github.com/rigetti/quil/tree/master/rfcs/analog).
Two new instructions
- FENCE-ALL
- SHIFT-FREQUENCY
one new frame attribute
- HARDWARE-OBJECT
and a new waveform.
=> Update Quilt Syntax

app/src/entry-point.lisp
This strips non-protoquil data (gate and circuit definitions, specifically) from the protoquil responses in quilc.
=> Omit circuit and gate definitions from protoquil responses

src/package.lisp
- Remove orphaned symbols that no longer have a definition
- Rename symbols to match new definition names
Discovered as part of work on #566
=> Maintenance on the external symbols of CL-QUIL

app/src/entry-point.lisp, app/src/globals.lisp, src/addresser/addresser-common.lisp, src/addresser/astar-rewiring-search.lisp, src/addresser/embed-swap.lisp, src/addresser/logical-schedule.lisp, src/addresser/path-heuristic.lisp, src/addresser/temporal-addresser.lisp, src/compilation-methods.lisp, src/compilers/approx.lisp, src/compressor/compressor.lisp, src/define-pragma.lisp, src/options.lisp
* replace `format *compiler-noise*` with `format-noise` which includes check to see if defined.
* `format-noise` includes fresh line.
=> encapsulate noise formatting

.gitlab-ci.yml, Makefile, src/quilt/package.lisp, tests/quilt/parser-tests.lisp
Export the following symbols from the CL-QUIL.QUILT package:
- `PARSED-QUILT-PROGRAM                   ; CLASS`
- `PARSED-PROGRAM-WAVEFORM-DEFINITIONS    ; READER`
- `PARSED-PROGRAM-CALIBRATION-DEFINITIONS ; READER`
- `PARSED-PROGRAM-FRAME-DEFINITIONS       ; READER`
The last three were previously exported from CL-QUIL, even though they no longer live there, and were removed from CL-QUIL exported symbols in #583.
`PARSED-QUILT-PROGRAM` was previously not exported anywhere, but seems reasonable to export as well.
Additionally, add a `test-quilt` Makefile target, and run it when running `make test`.
=> Reference PARSED-QUILT-PROGRAM accessors from the appropriate package

tests/printer-test-files/gold-regex/plundered-regex-gold.quil
A [recent update](https://github.com/soemraws/parse-float/commit/2d11b77647aa33efab31dbe0720b8fca9a274c81) to `PARSE-FLOAT` has changed the parsing of "0.3", which previously resulted in something like 0.30000000000000004 when printed, but now results in 0.3.
The new regex should be compatible with both old and new versions of `PARSE-FLOAT`.
Fixes #588
=> Fix floating point regex in plundered-regex-gold.quil

app/src/versions.lisp
=> If quilc is latest version, don't print the SDK version check log message

src/build-gate.lisp
- Coerce non-double reals to doubles
- Signal an explicit error for complexes
Fixes #434.
=> Better errors and coercing for param values

src/chip/chip-reader.lisp, src/compressor/compressor.lisp, src/define-compiler.lisp, tests/compilation-tests.lisp, tests/qpu-test-files/1q-free-rx.qpu
Closes #610. In an ISA, under the "gates" key one can specify a parameter value for which the gate is native. For example, on Aspen chips `RX` is native only for parameter values of `0`, `pi/2`, `pi`, `-pi/2`, and `-pi`. This restriction is occasionally baked-into the compiler, rather than just in the ISA. I remove that restriction, allowing freely parameterized RXs as the output of compilation:
```
;; produce a 1Q program on qubit 0, with 10 interleaved RX or RZ gates
(print-parsed-program (compiler-hook (random-1q-program 0 10) chip))
RX(0.8883713366102477) 0                # Entering rewiring: #(0)
RZ(-1.8883138383394045) 0
RX(2.8851948642306953) 0
```
where chip is given by this ISA:
```
{
"isa": {
"1Q": {
"0": {
"gates": [
{
"operator": "I",
"parameters": [],
"arguments": [
"_"
], …
```
=> Allow freely parameterized RX gates

src/clifford/benchmarking-procedures.lisp
=> Fix ZEROS not defined error in clifford benchmarking

src/ast.lisp
=> Disable *PRINT-CIRCLE* and use ~:P in PRINT-OBJECT for PARSED-PROGRAMs

src/addresser/logical-schedule.lisp, src/chip/chip-specification.lisp, src/compilers/euler-compile.lisp, src/compilers/translators.lisp, src/compressor/compressor.lisp, src/define-compiler.lisp, tests/compilation-tests.lisp
The computed compiler paths were:
(1) not returning the shortest path, though the function claimed to do
so; and
(2) not including XY compilers, even if the target gateset included an
XY gate that was better than a CZ gate on the same hardware object
This introduces a separate issue: arbitrarily long sequences of rx and
rz gates are not collapsed into at most five gates, but now collapse
into at most 7 gates. This is due to the compiler thinking that the
EULER-YZY compiler is better than the EULER-ZXZ compiler. I can live
with this regression for now, since the two extra gates don't cost much
in terms of fidelity, when compared to the improvement of allowing for
high-fidelity XY gates.
An extra nicety: we can now support SWAPs that compile to just two 2Q
gates (one XY and one CZ, cf. …
=> Fix compiler path calculation

src/define-compiler.lisp, tests/compilation-tests.lisp
Previously, a gate with unknown fidelity and n occurrences was
recorded in the metric as having one unknown. This means an occurrence
table of `{RX: 1, RY: 50}` with `RX` known and `RY` unknown would have a
better metric than `{RX: 2, RY: 1}` since the `RY` in both cases is recorded
as 1 unknown. This causes issues in determining short compiler paths.
This change now records the former table with 50 unknowns
and the latter with 1 unknown. This change also adds additional
documentation to the `OCCURRENCE-TABLE` structure to make this clear.
`TEST-RX-RZ-STRINGS-REDUCE` has been returned to its initial expectation
of five gates.
=> Account for number of gates of unknown fidelity in EVAL-OCC-TABLE

.travis.yml
This enables builds on travis, thus allowing PRs from external branches to trigger the testing pipelines.
=> Add .travis.yml build

boondoggle/src/pipeline.lisp
This was detected by a warning on the upcoming SBCL 2.0.7.
http://report.quicklisp.org/2020-07-24/failure-report/quilc.html#boondoggle
=> Fix UB of destructively modifying macro arguments

src/compilers/qs-compile.lisp, tests/compilation-tests.lisp
For some reason, QS-COMPILER allowed anonymous gates of fewer than 3
qubits. Issues around this arose while trying to make custom ISA files
and having typos in gate names. The issues would manifest themselves
as faulty calls to INST* with no qubit arguments (i.e., trying to
decompose a 1-qubit gate into 0-qubit "gates").
This commit also removes the check for the nativeness of a gate. If
this check persists, then CSWAP will not be compilable. Since CSWAP,
CCNOT, and CAN are the only listed native gates, I figure it's fine if
these gates hit this compiler.
=>  fix QS-COMPILER in certain edge cases of what it accepts

src/define-compiler.lisp, tests/compilation-tests.lisp
When we changed the way occ-tbl metrics were calculated, it caused
quilc to find particularly good collections of compilers ("compiler
paths") for certain gate sets. These particularly good compiler paths
were better than before! But there was a hitch... the better compilers
were also less flexible in what they matched against, though that
wasn't apparent from the binding patterns themselves. In particular,
in some cases, the better compilers were ones that also did _not_
accept symbolic parameters (e.g., a memory reference). This means
these better compilers failed to take into account inputs like
`RX(theta) 0` even though the pattern `RX(_) _` was compilable.
The fix in this commit has two facets:
- First, we use heuristics to determine if a compiler can accept
symbolic parameters. This …
=> ensure applicable symbolic-accepting compilers are included

cl-quil-tests.asd, cl-quil.asd, src/compilers/ansatz-search.lisp, tests/ansatz-search-tests.lisp
add a new matrix->ansatz function
This commit adds a new function MATRIX->ANSATZ useful for finding
matrices in a given form. It just boils down to a Nelder-Mead which is
particularly effective in many cases. This function can be used to
build compilers for relatively exotic gate sets, provided you've
discovered a function which can represent them.
=> Ansatz search

app/src/entry-point.lisp, app/src/options.lisp, cl-quil.asd, src/backends/common.lisp, src/backends/quil/quil-backend.lisp, src/package.lisp
Tell me, O compiler, of that ingenious backend who travelled far and wide after he had sacked the famous town of Aho-Ullman-Sethi-Lam. This PR introduces some protocols to formalize the notion of a "backend". QUILC so far has acted as a front-end for Quil. Included is a simple "no op" backend that just writes out Quil as UTF8 bytes.
We don't suggest that this will be the end-all be-all protocol; we have use-cases in mind and in development, and we expect that as actual backends get implemented, the shape of this code will change. As such, consider this a "germ" of sorts.
The PR includes:
- New command line options `--backend`, `--backend-options`, `--list-backends`, `--compile`, `--output`, as well as short versions.
- A new directory `backends` for implementations of backends, including …
=> Framework for implementing quilc backends

Makefile, README.md, build-app.lisp
Add POST_LOAD_ASDF_SYSTEMS which adds systems to be built and loaded in
the executable file. This allows for external sysytems to extend quilc
and be built into the executable without being part of the quilc system.
=> Add POST_LOAD_ASDF_SYSTEMS option to build

src/define-compiler.lisp
=> Call PRINT-OBJECT directly on compiler output gates

src/chip/chip-reader.lisp
i.e. the range [double-float-epsilon, 1 - double-float-epsilon]
We truncate perfect fidelities to less-than-perfect so that we have
some wiggle room when deciding what to do next. That less-than-perfect
fidelity was chosen to be 0.999, which I think (at least in theory)
could cause unexpected behaviour. Say for example you have one
instruction with a very good fidelity (say 0.999999) and another with
good fidelity (0.999). The compiler will truncate the former to 0.999,
and may then pick the second instruction for its output. The user is
then left thinking why is this instruction chosen over the superior
0.999999 instruction?
The user might then return to the compiler to inquire about the
resulting fidelity of the program, which it will report as 0.999 which
is fine if the compiler chose …
=> Truncate fidelities to the range (0, 1)

src/chip/chip-specification.lisp, src/compilers/approx.lisp
Allow providing `:xy` as `:architecture` to the various chip builders. Also brings the default fidelities to something more recent / less guess-y, at least for xy/piswap/cz.
Closes #582
=> Allow building xy chips

src/magicl-constructors.lisp
`EYE` wraps `MAGICL:EYE`, which may be provided with both a type and a value for the diagonal. Currently, `MAGICL:EYE` will `COERCE` the value to the type, if need be. However, `(complex double-float)` cannot be coerced to `double-float`, even if the imaginary part is zero. Every so often quilc tries to construct a double-float identity matrix, e.g. here https://github.com/rigetti/quilc/blob/master/src/compilers/approx.lisp#L201, and this will cause an error.
=> Do not use a default value in EYE

src/compressor/compressor.lisp, src/define-compiler.lisp, tests/compilation-tests.lisp
In `compute-applicable-reducers` we hope to narrow the list of `compilers` down to those that "improve the brevity of a gate sequence" subject to the restriction "without exiting a particular `gateset`". (The word "brevity" here is maybe a hold-over from a time when program length (duration?) was the cost function, and now it means fidelity?) In reality, it would also include compilers that did *at least as good* as others. This seems to cause trouble for certain ISAs and compilers.
For example, if your ISA contains `CZ 0 1`, `CPHASE(θ) 0 1`, *and* each has the same fidelity `fid` then the compiler can get into a loop where a `CPHASE(θ) 0 1` is compiled with `half-cphase-to-cz` and then the resulting `CZ` are compiled with `cz-to-cphase`, etc. Both of these compilers are present in the …
=> Only use "reducers" that strictly improve fidelity

src/addresser/addresser-state.lisp
In src/addresser/addresser-state.lisp slot lschedule in class
addresser-state had wrong type declaration. It was
LOGICAL-SCHEDULE. It should be LOGICAL-SCHEDULER.
This got exposed with the system compiled in SBCL with compiler policy
safety = 3. To reproduce I recompiled after clearing binaries and
evaluating the following before compiling and running tests:
(sb-ext:restrict-compiler-policy 'debug 3 3)
(sb-ext:restrict-compiler-policy 'safety 3 3)
(sb-ext:restrict-compiler-policy 'space 0 0)
(sb-ext:restrict-compiler-policy 'speed 0 0)
Then test test-logical-matrix-sanity would fail with error message
unknown type specifier: CL-QUIL::LOGICAL-SCHEDULE
As per SBCL doc here http://www.sbcl.org/manual/#Declarations-as-Assertions,
when
(or (>= safety 2) (>= safety speed 1))
the compiler …
=> Fix error in test-logical-matrix-sanity with high type safety on SBCL.

src/quilt/ast.lisp
Note that this is not for cl-quil itself but rather for cl-quil/quilt,
a separate system that depends on cl-quil.
Previously, frame-hash would mix the list of qubits into the hash.
However, since qubits are objects and not interned per their index, in
order to have the desired effect, the hash of the index of each qubit
should be used.  By analogy with CL's sxhash, frame-hash now has the
desireable property that two frames that are frame= have the same
hash.
In older versions of SBCL, in particular in 1.4.5.debian, which is the
version used for CI on the cl-quil main repo, sxhash would return the
same result for two non-equal structures of the same type no matter
their internal values.
SBCL's behavior was not technically a bug, but it was nonoptimal, and
that was improved upon in this …
=> Fix frame-hash to return same hash, portably, for two frame= frames.

cl-quil-tests.asd, cl-quil.asd, src/ast.lisp, src/clifford/benchmarking-procedures.lisp, src/compressor/compressor.lisp, src/csd.lisp, src/options.lisp, src/utilities.lisp, tests/clifford-tests.lisp
This PR does two things:
1. ~Adds a forwards and backwards compatible fix for the upcoming changes to MAGICL. it'll search for the `LAPACK-CSD` function from multiple packages.~ Updates MAGICL to 0.9.0 and removes deprecated systems.
2. Fixes a few errors caught by SBCL at compile-time.
=> Fix for magicl update and other sundries

app/src/chip-cache.lisp, app/src/entry-point.lisp, app/src/rpc-server.lisp, quilc.asd
This PR adds a chip cache used by the RPC endpoints, so the benefit is mostly felt by pyquil users. Produces a speedup between ~3s and ~4s based on some simple tests. You'll notice below that even a very simple compilation still takes an amount of time that scales with the size of the chip -- this is because the addresser state object is rebuilt on every compilation. Caching this also would provide a very nice win. For a future PR.
For example:
```
from pyquil import get_qc, Program
from time import time
qc = get_qc("30q-qvm", as_qvm=True)
p = Program("""CNOT 0 1""")
for i in range(4):
t = time()
print(qc.compile(p).program)
print(f"iteration {i} took \t {time() - t}s")
RZ(-pi/2) 1
RX(pi/2) 1
CZ 1 0
RZ(pi) 0
RX(pi/2) 0
RX(-pi/2) 0
RX(-pi/2) 1
RZ(pi/2) 1
HALT
iteration 0 took …
```
=> Cache chip specs between server requests

build-app.lisp
This allows the library-loading system to not depend solely on the
library name that was used at compile time. Example: If libffi.so.6
was used at compile time but is not present at run-time, then look for
alternatives rather than just failing.
Closes https://github.com/rigetti/pyquil/issues/1287
H/T https://gist.github.com/realark/1b6970a13615a6e389294ab9480d1e09
=> Load foreign libraries at run-time

src/package.lisp, src/quilt/analysis/expand-calibrations.lisp, src/quilt/analysis/fill-delays.lisp, src/quilt/analysis/resolve-objects.lisp, src/quilt/analysis/type-safety.lisp, src/quilt/ast.lisp, src/quilt/cl-quilt.lisp, src/quilt/parser.lisp
Eliminate use of package names with double colons (::) in Quilt, by
two methods: (1) exporting many semi-internal symbols to a new
package, cl-quil.si, and referring to them in that package; and (2) by
referring to symbols already exported (from CL-Quil) with a single
colon.
The new package, cl-quil.si (or quil.si, for short) is intended to
export system internal (SI) symbols, that is, some symbols not
generally intended to be used by the wider public, but more intended
for "friends" -- packages or facilities that are prepared to go a bit
below the surface level API.
References to most such symbols in Quilt, which previously referred to
quil::<symbol>, are changed in this commit to instead refer to
quil.si:<symbol>. (Quil.si is a nickname for cl-quil.si.)
In addition, the following …
=> introduce cl-quil.si package, eliminate :: refs in Quilt

cl-quil.asd, src/tools/package.lisp, tests/tools/package.lisp, tests/tools/suite.lisp
This is a stub for now, but we'll add to it later.
In anticipation of adding some dev-tools type modules, this introduces
a new subsystem cl-quil/tools that new modules can hang off of. For
now this is a stub, but later we may add, e.g., hasse-stuff (a little
utility for doing Hasse diagrams for logical schedulers) and circ-viz
(some tools for circuit visualization), maybe with different names.
The two anticipated new modules, and more to come later probably, are
not being added to cl-quil (core) system because they are
nice-to-haves but non-core. In addition, these two in particular have
weird dependencies like GraphViz and LaTeX, so cordoning them off
keeps the core a bit cleaner.
Issue "Print a logical-schedule as a Hasse diagram #712" relates
loosely to this in that Hasse stuff is …
=> Add subsystem cl-quil/tools -- cl-quil language tools for developers

.github/workflows/test.yml, .gitlab-ci.yml, build-app.lisp
1. Back in #702 I tried to get foreign libraries to load at run time vs. hard-coding library paths in the compiled executable. It was broken, however, so I reverted it a while back. Today I figured out how it was broken: when the libraries are "unloaded" and saved into a list, they're saved in reverse order. So when quilc is compiled the last library it links to is expokit because it depends on lapack which is loaded earlier. When I was loading from that list at run time I would end up trying to load expokit _before_ lapack, and CFFI would fail with an unhelpful error: instead of saying _why_ a library couldn't be loaded, it would just say that it couldn't be loaded. Anyhow, reversing the list fixes the problem. Have a good weekend.
2. I've changed the tests here to use a specific version …
=> Load foreign libraries at run time

tests/misc-tests.lisp
This fixes issue 723 in quil (not qvm). A subfunction of test function
test-measure-semantics in quil (%make-density-qvm-initialized-in-basis
in tests/misc-tests.lisp) had been calling qvm system and qvm package
function make-density-qvm with :amplitudes keyword. It turns out that
this argument was being ignored. Its being ignored was apparently not
a problem for this test.  However, in a more recent version of QVM,
the keyword arg began being passed along to make-instance on
DENSITY-QVM, and this is not a supported init arg, so the test
produced an error message like the following:
Invalid initialization argument:
:AMPLITUDES
in call for class #<STANDARD-CLASS QVM:DENSITY-QVM>.
The new code performs the desired functionality without the keyword
arg, and is actually simpler.
Resolves: …
=> [#723] fix error in test-measure-semantics due to change in qvm

src/gates.lisp, src/parser.lisp, src/quil/stdgates.quil, tests/compilation-tests.lisp, tests/parser-tests.lisp
add a new `BLOCH` gate for specifying a Bloch-sphere rotation (useful for typing random 1q unitaries)
=> add BLOCH gate & fix DEFGATE parsing bug

src/analysis/type-safety.lisp, src/ast.lisp, src/define-compiler.lisp, src/qasm.lisp, tests/printer-test-files/gold-regex/plundered-regex-gold.quil, tests/printer-tests.lisp, tests/translator-tests.lisp
This changeset provides support for Allegro CL 10.1 (modern cased
`mlisp` not supported). The updates are mostly concerned with floats
printer compatibility.
All tests passed for both Allegro and SBCL in a 64-bit Linux
environment, except these 4 take siginificantly longer time to even finish in Allegro:
* `test-compiler-hook`
* `test-sohaib-gh-361-regression`
* `test-compiler-hook-random-4q`
* `test-chp-files`
Therefore, in this _Part I_ PR, we only present updates that are only
concerned with "correctness". Hopefully, in _Part II_, we will present
optmizations that solves the performance problem.
Change-Id: I25ff3ac8e9a696b8550bebb828b87e0858a7268c
=> support AllegroCL 10.1 (Part I)

src/analysis/type-safety.lisp
[Issue 770](https://github.com/quil-lang/quilc/issues/770) is caused by
careless use of `apply`. This PR tries to fix it.
=> Fix issue 770

benchmarking/rewiring-analysis.lisp, cl-quil.asd, src/addresser/1q-queues.lisp, src/addresser/addresser-common.lisp, src/addresser/addresser-state.lisp, src/addresser/conditions.lisp, src/addresser/initial-rewiring.lisp, src/addresser/rewiring.lisp, src/chip/chip-specification.lisp, src/compilation-methods.lisp, tests/addresser-tests.lisp, tests/compiler-hook-tests.lisp, tests/initial-rewiring-tests.lisp
Using disconnected components.
Previously, we only supported allocating qubits in the program onto
the single largest component, precluding parallel program compilation,
regardless of whether the QPU topology supports it. Fix this and use a
greedy allocation scheme allowing more classes of programs to get
compiled onto QPUs with multiple connected components.
Conceptually, this is as if we combined mutliple QPUs into a
"multi-core" system, and we are now scheduling quil programs to use
them intelligently.
Fixes issue #74.
=> Teach the compiler how to compile parallel programs.

.github/workflows/test.yml, Makefile
Makefile
- add QVM to systems included by target dump-version-info target
.github/workflows/test.yml:
- unify all jobs to run the same way except for make target
- jobs now build with latest magicl and qvm cloned from official repo
Resolves issue #772: Github CI failing in test-cl-quil due to
Quicklisp's version of magicl being too old
=> various Github CI improvements for quilc

quilc.asd, src/ast.lisp
Recently @karlosz observed that for some of the quilc tests, a large amount of time was spent calling Lisp's `compile`. This appears to still be the case, but I think I've tracked it down. For *parametric programs* (which are not currently tested in the `benchmark-nq` routines we have), quilc needs to construct a map from parameter values to matrices for each gate definition being used. This is part of `gate-definition-gate` here https://github.com/quil-lang/quilc/blob/master/src/gates.lisp#L386
Although a parsed program like `RX(pi) 0; RX(pi) 1; RX(pi/2) 0` should end up with three applications, resolved to one gate definition (for "RX"), we were getting a new gate definition for every parametric gate application. The reason for this is that in the `simplify-arithmetic` pass, we were …
=> Preserve existing name resolution when copying gate application

.gitlab-ci.yml
.gitlab-ci.yml
- This Gitlab CI file .gitlab-ci.yml had fallen into disrepair and
disuse, so this revives it, syncs it with its Github counterpart
.github/workflows/test.yml, and adds a bit of extra functionality.
- Now it does the functionality of running the three cl-quil tests
in a similar way to what's done in Github but differs a little
because more stuff needs be done in the Ubuntu Linux instance in
Gitlab vs. in Github. Both CI's run in something called
"ubuntu:latest", but Github's is a VM with a lot more commonly
needed deps preinstalled, e.g., git, whereas Gitlab runs on the
very stripped-down Docker ubuntu:latest container. Apart from
these setup differences, the testing code should be almost the
same, although Gitlab permits the use of the "extends:" directive,
which saves …
=> fix issue #778: Gitlab YAML file doesn't work

benchmarking/quilc-mon-prof.lisp
I just noticed that I'd left in some code which is useless by
mistake. It causes style warnings, which this commit eliminates.
The useless code came along with new modules introduced in my recent
commits for cl-quil-benchmarking system.  Tested by running on command
line: make benchmark-nq
=> flush some unused code recently added in benchmarking code

lib/src/build-image.lisp, lib/src/libquilc.lisp, lib/tests/c/compile-protoquil.c, lib/tests/c/compile-quil.c, lib/tests/c/print-chip-spec.c, libquilc.asd
* Notably, we pull out handles into its own API so that other sbcl
librarian managed libraries can share the implementation. (And stuff
doesn't step on each other.)
=> Update to new SBCL librarian interface.

src/chip/chip-reader.lisp, src/chip/chip-specification.lisp, tests/compilation-tests.lisp, tests/qpu-test-files/swap.qpu
* Teach the chip reader how to deal with it.
* Adjust a test.
This just naively translates swap instructions directly when the
object supports it.
=> Teach the "old gate definition model" about SWAP.

src/addresser/addresser-state.lisp, src/addresser/fidelity-addresser.lisp, src/compilation-methods.lisp, src/compressor/compressor.lisp
When we have two equal fidelities resulting from an algebraically
reduced program, and an algebraically reduced decompiled program,
prefer the one that's shorter.
Fixes issue #801.
=> prefer shorter sequences during compression with decompilation

src/compilers/permutation.lisp, src/compilers/truth-table.lisp, tests/permutation-tests.lisp
Perm gates were being synthesized as inverses, leading to improper
compilations.
Added a battery of new tests for checking multi-qubit perm gate
synthesis.
Fixes #805.
=> fix permutation gate synthesis

cl-quil.asd, src/gates.lisp, src/initialize-standard-gates.lisp, src/package.lisp
It was discovered when fiddling with some of the std gate definitions that the recent sequence gate definition validation/resolution aren't fully integrated for sequence gate definitions added to this file
=> Bugfix: rework some of the standard gates init logic to accommodate seq gates 

Makefile, README.md, cl-quil.asd, src/discrete/discrete-chip.lisp, src/discrete/package.lisp, tests/discrete/package.lisp, tests/discrete/suite.lisp, tests/discrete/tests.lisp
This adds implementation and test **SCAFFOLDING** for "discrete compilation"—compilation of Quil programs to discrete gate sets—to QUILC. This does not actually contain an implementation, except for some minor defining functions.
The implementation will come later as a collaboration with other contributors. This PR is intended to help move that along by splitting the work up a bit.
=> Scaffolding for CL-QUIL/DISCRETE

app/src/entry-point.lisp, app/src/printers.lisp, src/addresser/initial-rewiring.lisp, src/matrix-operations.lisp, src/utilities.lisp
Description:
When using a tolerance pragma (e.g. `PRAGMA TOLERANCE "0.5"`), print global phase invariant distance ([arXiv:2106.07099](https://arxiv.org/abs/2106.07099)) instead of erroring when matrices are inevitably in the wrong projective class (e.g. `#Matrices have a phase invariant distance of 0.29746263355117152d0`).
Changes:
- If tolerance pragma, prevent matrix scaling error
- Make function for checking top pragmas
=> Add tolerance check

Makefile, app/src/entry-point.lisp, app/src/options.lisp, app/src/package.lisp, cl-quil.asd, quilc.asd, src/chip-library/chip-table.lisp, src/chip-library/package.lisp, tests/chip-library/chip-table-tests.lisp, tests/chip-library/package.lisp, tests/chip-library/suite.lisp
Defines a system for post-loading new arguments to `quilc --isa ...`.
Right now this is a separate system for two reasons:
- It keeps mutation out of `cl-quil`
- It isolates the development/archival of ISAs to a separate location
Semi-relevant issue:  #818
=> Add a new chip library system

src/compilers/translators.lisp
This allows programs like
```
DECLARE t REAL
CONTROLLED RX(t) 0 1
CONTROLLED RY(t) 0 1
CONTROLLED RZ(t) 0 1
```
to be compiled. It's unclear whether the forked compiler should handle these.
See https://github.com/quil-lang/quilc/issues/832 for details.
=> compile CONTROLLED R[XYZ] allowing symbolic parameters

src/compressor/compressor.lisp
Passes all tests, and produces output just as good as the original implementation on some basic benchmarks I ran.
(commits should probably be squashed)
=> Refactor `COMPRESS-INSTRUCTIONS`

src/compressor/compressor.lisp
=> Do not frighten future COMPRESS-INSTRUCTIONS spelunkers

.gitlab-ci.yml
The Gitlab CI pipeline was failing to load libcrypto (libssl-dev seemed not to be installed) and libffi (wanted an old version). With a little luck, this change installs them in the CI runner.
Note that this PR does not change Github actions; I'm not sure if those are broken or not.
=> Install additional dependencies in Gitlab CI

lib/Makefile, lib/src/libquilc.lisp, lib/tests/c/Makefile
This PR does two things:
- Use the `cl-quil` and `cl-quil.frontend` packages instead of `quil` when exporting functions in `libquilc.lisp`
- Fix an incorrect variable name in the Makefile for the libquilc C tests so that the `-pagezero_size 0x100000` flag gets passed on macOS
=> A couple of libquilc fixes

lib/src/build-image.lisp
This PR uses the `initialize-lisp-args` option introduced by quil-lang/sbcl-librarian#36 to increase the default heap size to 8 GiB when initializing the runtime in the bindings for libquilc.
Built libquilc against SBCL master with the bigger heap size on macOS, the `compile-quil` C test now runs without issue.
=> Increase heap size when initializing runtime for libquilc

src/compilers/approx.lisp, src/matrix-operations.lisp
It seems that LAPACK becomes unstable on ARM when attempting to find the eigenvectors and eigenvalues of a diagonal matrix. This instability is triggered in find-diagonalizer-in-e-basis. The operation becomes trivial when run on a diagonal matrix, so we check for this and return the identity to avoid making a potentially unstable LAPACK call.
Fixes #842.
=> check for diagonal matrices in find-diag-in-e-basis

src/frontend-options.lisp, src/initialize-standard-gates.lisp, src/package.lisp
Instead of inlined calls to `asdf:system-relative-pathname`, instead we offer a new exported variable `*default-standard-gates-file*`
=> abstract out stdgates.quil path to *default-standard-gates-file*

src/gates.lisp
Gate operator constructors `dagger-gate`, `forked-gate`, and `controlled-gate` formerly accepted any-ole value as a target argument. This PR makes `gate` the most general type they accept. 
Furthermore, I added `:type gate` slot option to the `:target` slot definition in the respective `defclass` forms.
=> Modify: gate operator classes take gates as their target

boondoggle/src/consumers.lisp, boondoggle/src/processors.lisp, boondoggle/src/producers.lisp, boondoggle/tests/tests.lisp, src/print-program.lisp
I ran the boondoggle tests like so:
cd <path-to>/qvm 
make qvm 
./qvm -S 
#elsewere ...
sbcl 
> (ql:quickload :boondoggle-tests) 
> (asdf:test-system :boondoggle) 
and they passed. 
Some notes: 
- I changed a `dotimes` to a `loop repeat` because unused and/or shadowed counter variables make me nervous. 
- I altered `print-parsed-program-generic` in a way that, in a more perfect world, would not be necessary, but that shouldn't hurt anything.
=> fixes (for) boondoggle: quil -> cl-quil; workaround in print-program

cl-quil-tests.asd, cl-quil.asd, src/compilers/sqisw-decomposition.lisp, src/frontend-utilities.lisp, src/package.lisp, src/quil/stdgates.quil, tests/sqisw-decomp-tests.lisp
Defines two mutually exclusive compiler rules that match CAN gates. One rule decomposes a CAN into two SQISWAP gates interleaved by 1 qubit rotations; call this the case-2 rule. The other rule, call it case-3, decomposes a CAN into an SQISWAP gate and another CAN gate to which case-2 is applicable. 
There are some inline "tests" in comment blocks that I have left in for the time being as an aid to understanding. I can remove them if desired. 
This PR partially addresses #766
=> Add: define-compiler decomposing CAN gates to <= 3 SQISWAP gates

src/backends/common.lisp
Two fixes. One: list-available-backends should return not classes but class names.
Two: the way it was written before, calling list-available-backends twice resulted in a hang leading to a heap overflow.
This change fixes quilc but does not address the issue, which may indicate a bug in sbcl.
=> Hotfix: list-available-backends; nconc causes evil behavior

src/chip-library/chip-table.lisp
Added `linear` and `fully-connected` to the available chips that could be called via the `call-chip-builder` function within `chip-library.lisp`.  They accept one argument, `nQ`, which is the number of qubits for which to build the chip.  They return a chip object same as all other chip-building functions do.
=> Call-Chip-Builder Function Accepts 'Linear' and 'Fully-Connected' Chips

src/discrete/numeric/cyclotomic8.lisp, src/discrete/numeric/interval.lisp, src/discrete/numeric/linear-algebra.lisp, src/discrete/numeric/root2plex.lisp, src/discrete/package.lisp, src/discrete/rz-approx/candidate-generation.lisp, src/discrete/rz-approx/generate-solution.lisp
a typeclass method named .* was causing an ambiguous accessor error
I have renamed scalar operators from things like `.*` to things like `s*`. 
Moreover, one (probably unrelated) additional regression: `generate-maform-output-with-double` was marked from monomorphization but it would not compile - an assertion failed. For now I have simply commented out the monomorphization directive and added a TODO note.
@eliaslfox @stylewarning
=> Fix: coalton struct regression

lib/.gitignore, lib/Makefile, lib/src/libquilc.lisp, lib/tests/c/.gitignore, lib/tests/c/Makefile, lib/tests/c/compile-protoquil.c
Modelled after e.g. [dlerror](https://linux.die.net/man/3/dlerror), the most recent error raised by `quilc` is captured in `*quilc-last-error*`. Calling `quilc-last-error` (or `quilc_last_error` depending on language) will
1. return the value in `*quilc-last-error*`; and
2. set `*quilc-last-error*` to `""`.
Obviously no guarantees around thread safety.
=> Add quilc_last_error function

cl-quil.asd, tests/discrete/rz-approx-tests.lisp
I ran into trouble getting sdiscrete tests to load and run:
1) I fixed some `.*` and `*.` to `s*` `*s` deprecated spots
2) There is an issue with a foreign function in the test `compile-rz`, so I commented the out (I think it's on the Magicl end). I can look into it, but wanted to get word out there first.
=> Fixing bugs to get discrete tests to load and run

cl-quil.asd, src/package.lisp, src/quilt/package.lisp
the cl-abstract-classes system available through quicklisp references a dead source URL. The author of this system, Tim Bradshaw, has factored this one system into two, renamed them, and changed he source URLS. This commit updates package and system names accordingly.
This commit has a sister commit in QVM, which also depends on abstract classes.
See also https://github.com/quil-lang/qvm/pull/318
=> updating deps for abstract and singleton classes

src/parser.lisp, tests/bad-test-files/bad-empty-vector.quil
If zero-length vectors are allowed, qvm crashes in `allocate-memory-for-model` with the error:
The value of QVM::SIZE is 0, which is not The SIZE wasn't a multiple of 8..
[Condition of type SIMPLE-TYPE-ERROR]
=> Forbid the declaration of zero-length classical vectors

src/cfg.lisp, tests/cfg-tests.lisp
Addresses #911 
Path contraction in the CFG construction was allowing for entry blocks to be removed, despite declaring such behavior to be illegal in the comment preceding that removal.
=> CFG path contraction condition was removing entry blocks

src/addresser/addresser-common.lisp, src/compiler-hook.lisp, src/package.lisp, src/pragmas.lisp
This PR adds a specialized PRAGMA for controlling the value of the `*addresser-rewiring-search-search-type*` special variable. This value defaults to :a* but two other options are available that have been previous unexposed to end-users. 
The PRAGMA introduced here has the following syntax: 
PRAGMA REWIRING_SEARCH <SEARCHTYPE>
Where `<SEARCHTYPE>` should be a string that names one of the available algorithms: `"A*"`, `"GREEDY_QUBIT"`, or `"GREEDY_PATH"`.
This PR is offered as a partial answer to #913 after discovering through experimentation that the offending program + chip spec discussed there compiled more quickly and with lower resource requirements after manually rebinding the `*addresser-rewiring-swap-search-type*` in the REPL.
It should be noted that I did not reproduce the exact …
=> Add PRAGMA to allow user control of swap search strategy

cl-quil.asd, src/tools/package.lisp, src/tools/unicode-diagram.lisp
Adds a textual circuit diagrammer to tools. 
e.g. 
``` lisp
(defvar parsed 
(cl-quil:parse-quil "
CONTROLLED H 0 1
CAN(1,2,3) 0 2
Y 0 
Z 1 
X 2 
SWAP 0 2
Z 2
CAN(pi/2,pi/2,pi/4) 1 2
SWAP 1 0
CNOT 1 0
SWAP 0 3
CNOT 0 1
CNOT 2 0
CONTROLLED CONTROLLED H 3 2 1
"))
(cl-quil:tools:print-program-diagram parsed)
```
prints
```
0                       1                        2             3
┬                       ┬                        ┬             ┬
│                       │                        │             │
│                      ╭┴╮                       │             │
·──────────────────────│H│                       │             │
│                      ╰┬╯                       │             │
│                       │                        │             │
│ …
```
=> Add unicode diagram printer for parsed-program instances

cl-quil.asd, src/package.lisp, src/quilt/package.lisp
Fixes #917 in conjunction with a [similar PR to QVM](https://github.com/quil-lang/qvm/pull/321)
This PR relies on a new dependency to quil-lang software called [clos-encounters](https://github.com/quil-lang/clos-encounters), which implements common OOP patterns presently in use in quilc and qvm. CLOS-ENCOUNTERS is meant to be a drop-in replacement for the tfeb abstract classes and singleton classes libraries that we have been using. 
The [tfeb libraries](https://github.com/tfeb/tfeb-lisp-hax) utilized lazy-loading of a dependency (`closer-mop`) in a manner that broke our build process. Because these OOP patterns are so easy to implement, we've simply done so here rather than making a PR tfeb's repo.
=> Add support for clos-encounters

.github/workflows/test.yml
CI fails because Quicklisp can't find `clos-encounters`, so this PR clones it into the same place as `magicl` and `qvm`.
=> Clone clos-encounters in CI workflows

benchmarking/foust/foust-benchmarking.lisp, cl-quil-benchmarking.asd, cl-quil-tests.asd, cl-quil.asd, src/coalton/README.md, src/coalton/coalton-quil.lisp, src/compressor/rewriting-rules.lisp, src/foust/README.md, src/foust/angle.lisp, src/foust/assignments.lisp, src/foust/circuit.lisp, src/foust/compile.lisp, src/foust/cost.lisp, src/foust/foust-quil.lisp, src/foust/foust-user.lisp, src/foust/foust.lisp, src/foust/frame.lisp, src/foust/gate.lisp, src/foust/graph.lisp, src/foust/graphviz.lisp, src/foust/node.lisp, src/foust/optimize.lisp, src/foust/pauli-operator.lisp, src/foust/pauli.lisp, src/foust/reduce.lisp, src/foust/sign.lisp, tests/foust/tests.lisp
This pull request adds a set of packages that build up an optimization routine, based on Intel's PCOAST, which takes advantage of the Clifford group as the normalizer of the Pauli group to perform global optimizations, including and especially in the context of measurements and preparations.
More details can be found in src/foust/README.md.
This commit does not integration to compiler-hook, which we expect in a follow-up commit and pull request.
=>  add a clifford-based optimizer module called foust to cl-quil
